### ISSUE TITLE
pyinstaller failed to execute script pyi_rth_pkgres

### ISSUE THREAD

**Issue by Leonsio21** [ao9000/tic-tac-toe-ai#2]
I have this erro after using: pyinstaller --onefile -w main.py

pyinstaller failed to execute script pyi_rth_pkgres

can anyone help me

**Comment by Leonsio21** [comment]
also i am using python 3.7.7 and i want to convert pygame file executable

**Comment by ao9000** [comment]
Hi

Kindly refer to the issue here: https://github.com/ao9000/tic-tac-toe-ai/issues/1
**The long story short,** one of the packages from pyinstaller has version compatibility issues. Just install a specific version to fix.

Also, in my codes, I have used walrus operator **:=** which is only available in Python 3.8 and above. So you might want to just use Python 3.8 or alternatively you can code substitutes for the operator.

Hope this helps
